language: python
python:
  - "3.6"
cache: pip
install:
  - pip install pushbullet.py
  - pip install -r requirements.txt
  - pip install python-coveralls
script:
  - coverage run -m unittest discover
  - coverage report --include="bioseq/*"
after_failure:
  - python pushbullet_notify.py "FAILURE"
after_success:
  - coveralls -b "bioseq"
  - python pushbullet_notify.py "SUCCESS"

notifications:
  email: false
